### ISSUE TITLE
TotalBeachVolume [m3] (grid_y, grid_x): Integrated sum of beached volume across all runs.

### ISSUE THREAD

**Issue by SusanEAllen** [MIDOSS/Visualization#3]

**Comment by SusanEAllen** [comment]
I've been thinking about this one and I think one thing we would like to get is mean beached volume if beaching occurs.  I'm thinking it would be good to include only those runs with significant (aka > 15L) beaching.  So we need the integrates sum of beached volume across all runs with significant beaching and the number of runs with significant beaching.

**Comment by SusanEAllen** [comment]
Also see comments on SurfaceVolume_sumsum and log transforming.

**Comment by RachaelDMueller** [comment]
What I’m hearing is that in addition to `TotalBeachVolume` > min beached volume threshold (still TBD), you would like a `TotalBeachVolume` > significant volume threshold.  Or am I already accounting for this request with existing `TotalBeachVolume`?  For number of runs, do you want me to explicitly add a number or is the list of runs that went into the netcdf sufficient (from which the length of the list can be used to give number of runs)?

**Comment by SusanEAllen** [comment]
min beached volume threshold and significant volume threshold are the same.
For number of runs, I want the number > threshold, not the total number of runs.  That is, if there is oil on the beach, what is the average amount of oiling?
