### ISSUE TITLE
SurfacePresence [no units] (grid_y, grid_x): [1] where maximum oil across time and runs is greater than our surface volume threshold; [0] elsewhere.

### ISSUE THREAD

**Issue by SusanEAllen** [MIDOSS/Visualization#5]

**Comment by SusanEAllen** [comment]
For each run it will be 1 if surface volume is significant at any time during the run (aka > 3L), but across runs it should be the sum (and we need the number of runs).

**Comment by RachaelDMueller** [comment]
Agreed. This is what I have in mind too.
